version: "3.9"

services:
    db-migrations-workshop-sre:
        container_name: db-migrations-workshop-sre
        build:
            context: ../../../
            dockerfile: ./.devops/docker/develop/Dockerfile

        depends_on:
            - db-postgres-workshop-sre
        volumes:
            - ../../../:/var/www/app
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

    db-postgres-workshop-sre:
        image: postgres:14
        container_name: db-postgres-workshop-sre
        environment:
            POSTGRES_PASSWORD: "shtwkj211283sss"
            POSTGRES_USER: "user_sre"
            POSTGRES_DB: "workshop_sre"
        volumes:
            - ~/storage_block/workshop/postgres/data:/var/lib/postgresql/data
        ports:
            - 5438:5432

#docker network create migrations-workshop-sre-network
networks:
    default:
        external:
            name: workshop-sre-network
